version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    networks:
      - app_network
    volumes:
      - ./app:/app
    environment:
      - STREAMLIT_PORT=8501
      - API_PORT=8000

networks:
  app_network:
    driver: bridge
