version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000

  frontend:
    build: .
    ports:
      - "8501:8501"
    command: bash -c "sleep 5 && streamlit run ./app/interface.py --server.port 8501 --server.address 0.0.0.0"
    depends_on:
      - backend
