name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Installer Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
    - name: Build the Docker image
      run: docker-compose -f ./melissa_technicaltest/docker-compose.yml up --build -t MOKHTARIMelissa/melissa_technicaltest_app:latest
    - name: push image to docker hub
      run: docker push MOKHTARIMelissa/melissa_technicaltest_app:latest
